version: '3.9'

services:
 web:
 
   build: .
   
   command: gunicorn text_summarizer.wsgi:application --bind 0.0.0.0:8000
                      
   expose: 
   - "80:8000"

   restart: "on-failure"
