version: '3.9'

services:
 web: 
   build: .   
   command: gunicorn --workers=4 text_summarizer.wsgi:application --bind 0.0.0.0:8000                    
   ports: 
   - 80:8000
   restart: "on-failure"
